class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'English': {
      'new_chat': 'New Chat',
      'authority_locator': 'Authority Locator',
      'emergency_sos': 'Emergency SOS',
      'daily_update_dashboard': 'Daily Update Dashboard',
      'documentation_templates': 'Documentation Templates',
      'ipc_section_finder': 'IPC Section Finder',
      'chat_history': 'Chat History',
      'no_chat_history': 'No chat history yet.',
      'logout': 'Logout',
      'guest_user': 'Guest User',
      'legal_awareness': 'Legal Awareness',
      'daily_legal_tip': 'Daily Legal Tip',
      'did_you_know': 'Did you know?',
      'find_legal_authorities': 'Find Legal Authorities Near You',
      'police_stations': 'Police Stations',
      'courts': 'Courts',
      'lawyers_advocates': 'Lawyers & Advocates',
      'legal_aid_clinics': 'Legal Aid Clinics',
      'emergency_assistance': 'Emergency Assistance',
      'domestic_violence': 'Domestic Violence',
      'cyber_fraud': 'Cyber Fraud / Scam',
      'police_arrest': 'Police Arrest Situation',
    },
    'Hindi': {
      'new_chat': 'नया चैट',
      'authority_locator': 'अधिकारी लोकेटर',
      'emergency_sos': 'आपातकालीन एसओएस',
      'daily_update_dashboard': 'दैनिक अपडेट डैशबोर्ड',
      'documentation_templates': 'दस्तावेज़ीकरण टेम्प्लेट',
      'ipc_section_finder': 'आईपीसी धारा खोजक',
      'chat_history': 'चैट इतिहास',
      'no_chat_history': 'अभी तक कोई चैट इतिहास नहीं।',
      'logout': 'लॉग आउट',
      'guest_user': 'अतिथि उपयोगकर्ता',
      'legal_awareness': 'कानूनी जागरूकता',
      'daily_legal_tip': 'दैनिक कानूनी युक्ति',
      'did_you_know': 'क्या आपको पता था?',
      'find_legal_authorities': 'अपने आस-पास के कानूनी अधिकारी खोजें',
      'police_stations': 'पुलिस स्टेशन',
      'courts': 'अदालतें',
      'lawyers_advocates': 'वकील और अधिवक्ता',
      'legal_aid_clinics': 'कानूनी सहायता क्लीनिक',
      'emergency_assistance': 'आपातकालीन सहायता',
      'domestic_violence': 'घरेलू हिंसा',
      'cyber_fraud': 'साइबर धोखाधड़ी',
      'police_arrest': 'पुलिस गिरफ्तारी की स्थिति',
    },
    'Tamil': {
      'new_chat': 'புதிய அரட்டை',
      'authority_locator': 'அதிகார இருப்பிடக் கண்டுபிடிப்பான்',
      'emergency_sos': 'அவசர உதவி (SOS)',
      'daily_update_dashboard': 'தினசரி புதுப்பிப்பு கட்டுப்பாட்டகம்',
      'documentation_templates': 'ஆவணங்கள் படிவங்கள்',
      'ipc_section_finder': 'IPC பிரிவு கண்டுபிடிப்பான்',
      'chat_history': 'அரட்டை வரலாறு',
      'no_chat_history': 'இதுவரை அரட்டை வரலாறு இல்லை.',
      'logout': 'வெளியேறு',
      'guest_user': 'விருந்தினர் பயனர்',
      'legal_awareness': 'சட்ட விழிப்புணர்வு',
      'daily_legal_tip': 'தினசரி சட்ட குறிப்பு',
      'did_you_know': 'உங்களுக்கு தெரியுமா?',
      'find_legal_authorities': 'உங்கள் அருகில் உள்ள சட்ட அதிகாரிகளை தேடுக',
      'police_stations': 'காவல் நிலையங்கள்',
      'courts': 'நீதிமன்றங்கள்',
      'lawyers_advocates': 'வழக்கறிஞர்கள்',
      'legal_aid_clinics': 'சட்ட உதவி மையங்கள்',
      'emergency_assistance': 'அவசர உதவி',
      'domestic_violence': 'குடும்ப வன்முறை',
      'cyber_fraud': 'இணைய மோசடி',
      'police_arrest': 'காவல்துறை கைது நிலை',
    },
    'Telugu': {
      'new_chat': 'కొత్త చాట్',
      'authority_locator': 'అథారిటీ లొకేటర్',
      'emergency_sos': 'అత్యవసర SOS',
      'daily_update_dashboard': 'రోజువారీ నవీకరణ డాష్‌బోర్డ్',
      'documentation_templates': 'డాక్యుమెంటేషన్ టెంప్లేట్లు',
      'ipc_section_finder': 'IPC సెక్షన్ ఫైండర్',
      'chat_history': 'చాట్ చరిత్ర',
      'no_chat_history': 'ఇప్పటికీ చాట్ చరిత్ర లేదు.',
      'logout': 'లాగ్అవుట్',
      'guest_user': 'అతిథి వినియోగదారుడు',
      'legal_awareness': 'న్యాయ అవగాహన',
      'daily_legal_tip': 'రోజువారీ చట్టపరమైన చిట్కా',
      'did_you_know': 'మీకు తెలుసా?',
      'find_legal_authorities': 'మీ సమీపంలో న్యాయ అధికారులను కనుగొనండి',
      'police_stations': 'పోలీస్ స్టేషన్లు',
      'courts': 'కోర్టులు',
      'lawyers_advocates': 'న్యాయవాదులు',
      'legal_aid_clinics': 'న్యాయ సహాయ క్లినిక్‌లు',
      'emergency_assistance': 'అత్యవసర సహాయం',
      'domestic_violence': 'గృహ హింస',
      'cyber_fraud': 'సైబర్ మోసం',
      'police_arrest': 'పోలీసు అరెస్టు పరిస్థితి',
    },
    'Kannada': {
      'new_chat': 'ಹೊಸ ಚಾಟ್',
      'authority_locator': 'ಅಧಿಕಾರ ಲೊಕೇಟರ್',
      'emergency_sos': 'ತುರ್ತು SOS',
      'daily_update_dashboard': 'ದೈನಂದಿನ ನವೀಕರಣ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'documentation_templates': 'ದಾಖಲಾತಿ ಟೆಂಪ್ಲೇಟ್‌ಗಳು',
      'ipc_section_finder': 'IPC ವಿಭಾಗ ಶೋಧಕ',
      'chat_history': 'ಚಾಟ್ ಇತಿಹಾಸ',
      'no_chat_history': 'ಇನ್ನೂ ಯಾವುದೇ ಚಾಟ್ ಇತಿಹಾಸವಿಲ್ಲ.',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'guest_user': 'ಅತಿಥಿ ಬಳಕೆದಾರ',
      'legal_awareness': 'ಕಾನೂನು ಅರಿವು',
      'daily_legal_tip': 'ದೈನಂದಿನ ಕಾನೂನು ಸಲಹೆ',
      'did_you_know': 'ನಿಮಗೆ ತಿಳಿದಿತ್ತೇ?',
    },
    'Malayalam': {
      'new_chat': 'പുതിയ ചാറ്റ്',
      'authority_locator': 'അധികാര പ്രദേശികം സംബന്ധിച്ച വിവരങ്ങൾ',
      'emergency_sos': 'അടിയന്തര SOS',
      'daily_update_dashboard': 'പ്രതിദിന അപ്‌ഡേറ്റ് ഡാഷ്‌ബോർഡ്',
      'documentation_templates': 'ഡോക്യുമെന്റേഷൻ ടെംപ്ലേറ്റുകൾ',
      'ipc_section_finder': 'ഐപിസി സെക്ഷൻ ഫൈൻഡർ',
      'chat_history': 'ചാറ്റ് ചരിത്രം',
      'no_chat_history': 'ഇതുവരെ ചാറ്റ് ചരിത്രമില്ല.',
      'logout': 'ലോഗ്ഔട്ട്',
      'guest_user': 'അതിഥി ഉപയോക്താവ്',
      'legal_awareness': 'നിയമ ബോധവൽക്കരണം',
      'daily_legal_tip': 'പ്രതിദിന നിയമ നുറുങ്ങ്',
      'did_you_know': 'നിങ്ങൾക്കറിയാമോ?',
    },
  };

  static String get(String language, String key) {
    // Default to English if the language or key is missing
    final langMap = translations[language] ?? translations['English']!;
    return langMap[key] ?? translations['English']![key] ?? key;
  }
}
